version: "3"

services:
  postgres:
    container_name: weather-postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - weather-app
    restart: always

  # backend:
  #   container_name: weather-backend
  #   image: weather-backend
  #   build:
  #     context: ./backend
  #     dockerfile: ./dev.Dockerfile
  #   depends_on:
  #     - postgres
  #   env_file:
  #     - .env
  #   ports:
  #     - 3000:3000
  #     - 5555:5555
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   networks:
  #     - weather-app
  #   restart: always

  frontend:
    container_name: weather-frontend
    image: weather-frontend
    build:
      context: ./frontend
      dockerfile: ./dev.Dockerfile
    # depends_on:
    #   - backend
    env_file:
      - .env
    ports:
      - 80:80
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - weather-app
    restart: always

networks:
  weather-app:
    name: weather-app

volumes:
  database:
